version: '3.8'
services:
  core-be:
    container_name: fit-mind-core-be
    image: fitmind/core-be:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI=http://fit-mind-keycloak:8090/realms/fitness-tracker
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://fit-mind-keycloak:8090/realms/fitness-tracker
      - KEYCLOAK_SERVICE_URL=http://fit-mind-keycloak:8090
    networks:
      - fit-mind-network
    depends_on:
      keycloak:
        condition: service_healthy

  users-be:
    container_name: fit-mind-users-be
    image: fitmind/users-be:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI=http://fit-mind-keycloak:8090/realms/fitness-tracker
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://fit-mind-keycloak:8090/realms/fitness-tracker
      - KEYCLOAK_SERVICE_URL=http://fit-mind-keycloak:8090
    networks:
      - fit-mind-network
    depends_on:
      keycloak:
        condition: service_healthy

  frontend:
    container_name: fit-mind-fe
    image: fitmind/fe:latest
    ports:
      - "3000:3000"
    environment:
      - CORE_BE_URL=http://fit-mind-core-be:8081
      - USERS_BE_URL=http://fit-mind-users-be:8082
      - NEXTAUTH_URL=http://fit-mind-fe:3000
    networks:
      - fit-mind-network
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    container_name: fit-mind-keycloak
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    ports:
      - "8090:8090"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=fit-mind-keycloak
      - KC_HOSTNAME_PORT=8090
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
    command: start-dev --http-port=8090 --import-realm --health-enabled=true --hostname=fit-mind-keycloak
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - fit-mind-network
    healthcheck:
      test: ["CMD", "curl", "--head", "-fsS", "http://localhost:8090/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  fit-mind-network:
    driver: bridge 